### PR TITLE
Fixed a value

### PR DESCRIPTION
**Pull request by ghost**
Same as previous pull request but without potential problems.

### CODE REVIEW

**Comment by ipa-rmb** [comment]
Can you merge with the latest squirrel-project:indigo_dev version. I just like to see that Travis times out at 50 minutes.

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
Strange stuff. I have no problem both on my machine and the robot but on the robot it actually takes forever. I will take the time to check how long it takes to compile on the robot, meanwhile I close the pull request.

**Comment by ipa-rmb** [comment]
The Pull Request is fine, you may leave it open. Travis always aborts after 50 minutes of compiling, that's a limitation of the free version. Hence I would just accept the PR if it compiles until Travis fails after 50 minutes, and that is the case. Just reopen it, if the PR is technically ok from your side.

**Pull request closed without merging**
